### PR TITLE
Jenkins 46233 build env settings

### PR DESCRIPTION
**Pull request by sparkoo**
https://issues.jenkins-ci.org/browse/JENKINS-46233
 - added "global" settings for Vagrantfile and VagrantVm
 - this global settings is taken when particular step's field is empty

benefit => user don't have to refill same vagrantfile/vagrantvm to each step, but still have power to do so.

### CODE REVIEW

**Comment by sparkoo** [comment]
@ShimiTaNaka can you please take a look?

**Comment by ShimiTaNaka** [comment]
I have. please:
1. squash the commits into a single one
2. Make sure the tests passes (Run `mvn test` in the project)

**Comment by ShimiTaNaka** [comment]
@sparkoo Fixed the tests issues, please just squash the commits

**Comment by sparkoo** [comment]
@ShimiTaNaka 
1. can you use "Squash and merge" here on github? I would have to create new branch and new PR.
2. what was the issue?

**Pull request merged**
